<?php
// $Id:

/**
 * @author: Matthew Messmer
 *
 *
 */

function histogram_menu() {
  $items['admin/config/media/histogram'] = array(
    'title' => 'Histogram',
    'page callback' => 'histogram_admin_settings',
    'access arguments' => array('administer image metadata'),
    'description' => t('Display available fields'),
    'access callback' => 'user_access',
    'file' => 'histogram.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/media/histogram/general'] = array(
    'title' => 'Histogram',
    'page callback' => 'histogram_admin_settings',
    'access arguments' => array('administer image metadata'),
    'description' => t('Display available fields'),
    'access callback' => 'user_access',
    'file' => 'histogram.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/config/media/histogram/settings'] = array(
    'title' => 'Histogram Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('histogram_admin_settings_form'),
    'access arguments' => array('administer image metadata'),
    'description' => t('Images Histogram Settings'),
    'access callback' => 'user_access',
    'file' => 'histogram.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_help().
 */
function histogram_help($path, $arg) {
  include_once drupal_get_path('module', 'histogram') . '/histogram.admin.inc';
  switch ($path) {
    case 'admin/help#histogram':
      return histogram_admin_settings();
  }
}

/**
 * Implements hook_permission().
 */
function histogram_permission() {
  return array(
    'administer image histogram' => array(
      'title' => t('Administer image Histogram'),
    ),
  );
}

function histogram_generate_histogram($object_type, $object) {
  $type = $object->type;
  $fields = field_info_instances($object_type, $type); //returns all fields on node
  $histogram_fields = _histogram_get_histogram_fields($fields); //returns array of histogram fields on node
  $image_fields = _histogram_get_image_fields($object_type, $object, $fields); //returns all image fields on node
  $image_fields_settings = _histogram_get_image_fields_settings($object_type, $object, $histogram_fields, $image_fields); //returns image_field uri and language
  foreach ($histogram_fields as $key => $value) {
    $field_name = $key;
    $histogram = NULL;
    if (property_exists($object, $field_name)) {
      $histogram = $object->$field_name;
    }
    $language = $value['language'];
    $imageURI = $image_fields_settings[$value['image_field']]['uri'];
    $bgcolor = $histogram[$language][0]['bgcolor'];
    $forcebw = $histogram[$language][0]['forcebw'];
    $histType = $histogram[$language][0]['histtype'];

    if (isset($imageURI)) {
      include_once drupal_get_path('module', 'histogram') . '/histogram.php';
      $histogram_path = histogram_make_histogram($imageURI, $bgcolor, $forcebw, $histType);

      $histogram[$language][0]['name'] = $histogram_path[0];
      $histogram[$language][0]['update'] = 0;
      $histogram[$language][0]['histovalues'] = serialize($histogram_path[1]);

      $object->$field_name = $histogram;
    }
  }
}

/**
 * implementation of hook_field_attach_presave.
 *
 */
function histogram_field_attach_presave($object_type, $object) {
  if ($object_type == 'node' && (_histogram_check_for_procesing($object_type, $object))) {
    histogram_generate_histogram($object_type, $object);
  }
}

/**
 * Check to see if this node type contains an image field that is selected for histogram processing
 * Only runs for nodetypes selected in admin/config/media/histogram/settings
 *
 * @return boolean
 */
function _histogram_check_for_procesing($object_type, $object) {
  $node_type = $object->type;
  $histogram_node_types = array();
  //fill up array with checked nodetypes
  foreach (variable_get('histogram_nodetypes', array()) as $type) {
    if ($type != "0") {
      $histogram_node_types[] = $type;
    }
  }
  //check $histogram_node_types vs current node type
  if (in_array($node_type, $histogram_node_types)) {
    //if true, this is a node type that has histogram processing
    //in this case, we must check to see if the histogram processing variable has been selected
    $fields = field_info_instances($object_type, $node_type);
    $histogram_fields = _histogram_get_histogram_fields($fields);
    foreach ($histogram_fields as $key => $value) {
      $field_name = $key;
      $field_image_name = $value['image_field'];
      $field_image = $object->$field_image_name;
      $language = _histogram_get_image_language($object, $field_image);
      if ($language == FALSE) {
        return FALSE;
      }
      else {
        $histogram = NULL;
        if (property_exists($object, $field_name)) {
          $histogram = $object->$field_name; //und->0->'name'
        }
        $update = $histogram[$language][0]['update'];
        if ($update == 1) {
          return TRUE;
        }
      }
    }
  }
  return FALSE;
}

/**
 * Returns histogram settings from widget, specifically the selected image field
 *
 */
function _histogram_get_histogram_fields($fields) {
  $result = array();
  foreach ($fields as $key => $value) {
    if ($value['widget']['type'] == 'histogram_widget') {
      $element = array();
      $element['image_field'] = $value['widget']['settings']['image_field'];
      $result[$key] = $element;
    }
  }
  return $result;
}

/**
 * Returns image fields on node
 * @param $object_type
 * @param $object
 */
function _histogram_get_image_fields($object_type, $object, $fields) {
  $result = array();
  if ($object_type == 'node') {
    foreach ($fields as $key => $value) {
      if (is_array($value) && is_array($value['widget']) && $value['widget']['type'] == 'image_image') {
        $result[$key] = $value;
      }
    }
  }
  return $result;
}

/**
 * Filters out unneeded fields from image_fields array
 */
function _histogram_get_image_fields_settings($object_type, $object, &$histogram_fields, $image_fields) {
  $result = array();
  if (empty($histogram_fields)) {
    return TRUE;
  }
  if (empty($image_fields)) {
    return FALSE;
  }
  foreach ($histogram_fields as $key => $value) {
    $field_image_name = $value['image_field'];
    if (empty($image_fields[$field_image_name])) {
      $result[$field_image_name] = array();
    }
    else {
      $image_descriptor = _histogram_get_file_uri_and_language($object, $field_image_name, $object_type);
      $result[$field_image_name] = $image_descriptor;
      $histogram_fields[$key]['language'] = $image_descriptor['language'];
    }
  }
  return $result;
}

/**
 * Returns image uri and language
 */
function _histogram_get_file_uri_and_language($object, $field_image_name, $object_type) {
  if ($object_type == 'node') {
    $result = array();
    //then check it is an array
    if (!is_array($object->$field_image_name)) {
      return FALSE;
    }
    else {
      $field_image = $object->$field_image_name;
      $language = _histogram_get_image_language($object, $field_image);
      if ($language == FALSE) {
        return FALSE;
      }
      else {
        $fid = _histogram_get_image_fid($field_image, $language);
        if ($fid == FALSE) {
          return FALSE;
        }
        else {
          $file = file_load($fid);
          $result['uri'] = $file->uri;
          $result['language'] = $language;
        }
      }
    }
  }
  return $result;
}

function _histogram_get_image_language($object, $field) {
  if (property_exists($object, 'language')) {
    if (array_key_exists($object->language, $field)) {
      return $object->language;
    }
    else {
      if (array_key_exists('und', $field)) {
        return 'und';
      }
      else {
        return FALSE;
      }
    }
  }
  else {
    return FALSE;
  }
}

function _histogram_get_image_fid($field, $language) {
  if (is_array($field[$language])) {
    if (!empty($field[$language]) && is_array($field[$language][0])) {
      $localized_field = $field[$language][0];
    }
    else {
      return FALSE;
    }
  }
  else {
    return FALSE;
  }
  $fid = $localized_field['fid'];
  return $fid;
}

/**
 * Implementation of hook_field_info().
 */
function histogram_field_info() {
  return array(
    'histogram' => array(
      'label' => t('Histogram'),
      'description' => t('Histogram field.'),
      'default_widget' => 'histogram_widget',
      'default_formatter' => 'histogram_formatter',
    ),
  );
}

/**
 * Implements hook_field_widget_info().
 */
function histogram_field_widget_info() {
  return array(
    'histogram_widget' => array(
      'label' => t('Histogram widget'),
      'description' => t('field content is calculated from image field in the same content type (read only)'),
      'field types' => array('histogram'),
      'settings' => array(
        'image_field' => '',
      ),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_DEFAULT,
        'default value' => FIELD_BEHAVIOR_DEFAULT,
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function histogram_field_formatter_info() {
  return array(
    'histogram_formatter' => array(
      'label' => t('Default'),
      'field types' => array('histogram'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function histogram_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'histogram_formatter':
      foreach ($items as $delta => $item) {
        $element[$delta]['#markup'] = theme('histogram_formatter_default', $item);
      }
      break;
  }

  return $element;
}

/**
 * Implementation of hook_field_is_empty().
 */
function histogram_field_is_empty($item, $field) {
  if ($field['type'] == 'histogram') {

    if (empty($item['name']) && empty($item['histovalues']) && empty($item['histtype']) && empty($item['forcebw']) && empty($item['update']) && empty($item['bgcolor'])) {
      return TRUE;
    }

  }
  return FALSE;
}

/**
 * Implementation of hook_field_settings_form().
 */
function histogram_field_settings_form($field, $instance, $has_data) {
  if ($field['type'] == 'histogram') {
    $form = array();
    $form['#attached']['css'][] = drupal_get_path('module', 'histogram') . '/histogram-field-settings-form.css';
    return $form;
  }
}


/**
 * Implementation of hook_field_widget_form().
 */
function histogram_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $form['#attached']['css'][] = drupal_get_path('module', 'histogram') . '/histogram.css';
  $element_info = element_info($field['type']);
  $element += array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $element['name'] = array(
    '#type' => 'hidden',
    '#default_value' => isset($items[$delta]['name']) ? $items[$delta]['name'] : NULL,
  );
  $element['histovalues'] = array(
    '#type' => 'hidden',
    '#default_value' => isset($items[$delta]['histovalues']) ? $items[$delta]['histovalues'] : NULL,
  );
  $element['update'] = array(
    '#type' => 'radios',
    '#title' => t('Generate Histogram'),
    '#options' => array(
      1 => t('Yes'),
      0 => t('No'),
    ),
    '#default_value' => isset($items[$delta]['update']) ? $items[$delta]['update'] : 1,
    '#description' => t('Select "Yes" to generate a histogram. This should be set to "Yes" the first time the node is saved or any time the options below are changed.'),
  );
  $element['histtype'] = array(
    '#type' => 'radios',
    '#title' => t('Histogram Type'),
    '#options' => array(
      0 => t('Stacked'),
      1 => t('Combined'),
    ),
    '#default_value' => isset($items[$delta]['histtype']) ? $items[$delta]['histtype'] : 0,
    '#description' => t('Generate a stacked histogram with three seperate color channels or a merged combined histogram.'),
  );
  $element['forcebw'] = array(
    '#type' => 'radios',
    '#title' => t('Force Single Channel Histogram'),
    '#options' => array(
      0 => t('No'),
      1 => t('Yes'),
    ),
    '#default_value' => isset($items[$delta]['forcebw']) ? $items[$delta]['forcebw'] : 0,
    '#description' => t('Force generation of a single channel black and white histogram. Useful on an image by image basis in cases of tinted monochrome images where the automatic monochrome detection fails'),
  );
  $element['bgcolor'] = array(
    '#type' => 'textfield',
    '#title' => t('Histogram Background Color'),
    '#default_value' => isset($items[$delta]['bgcolor']) ? $items[$delta]['bgcolor'] : '000000',
    '#description' => t('Background color in hexadecimal numbers. Leave blank for transparent background.'),
    '#element_validate' => array('_histogram_hexadecimal_validate'),
  );
  return $element;
}


/**
 * Validation callback for a hexadecimal element.
 */
function _histogram_hexadecimal_validate($element, &$form_state, $form) {
  $value = $element['#value'];
  if (empty($value)) {
  }
  else if ($value[0] != "#") {
    $value = "#" . $value;
    if (preg_match('/^#[a-f0-9]{6}$/i', $value)) {
    }
    else {
      form_error($element, t('Please enter a valid hexadecimal number'));
    }
  }
}


function histogram_theme($existing, $type, $theme, $path) {
  return array(
    'histogram_formatter_default' => array(
      'variables' => array('item' => NULL),
    ),
  );
}


function theme_histogram_formatter_default($item) {

  $output = '';
  //$output .= '<div class="histogram">';
  $output .= '<img class="histogram" src="';
  $output .= url($item['name']);
  $output .= '" >';
  //$output .= '</div>';

  return $output;
}


/**
 * Implementation of hook_widget_settings().
 */
function histogram_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $defaults = field_info_widget_settings($widget['type']);
  $settings = array_merge($defaults, $widget['settings']);

  $form = array();
  if ($widget['type'] == 'histogram_widget') {
    if ($instance['entity_type'] == 'node') {
      $image_fields = _histogram_field_widget_retreive_image_field_from_bundle($instance['entity_type'], $instance['bundle']);
      $default_image_value = _histogram_get_field_widget_retreive_image_field_default_value($widget, $image_fields);
      $form['image_field'] = array(
        '#type' => 'radios',
        '#title' => t('Image Field'),
        '#description' => t('Select the image field to be used when generating the histogram'),
        '#options' => $image_fields,
        '#default_value' => $default_image_value,
        '#element_validate' => array('_histogram_field_widget_image_field_validate'),
      );
    }
  }
  return $form;
}


/**
 * retreive all image_field fields of the same content type (bundle)
 * @param $bundle_name
 */
function _histogram_field_widget_retreive_image_field_from_bundle($entity_type, $bundle_name) {
  $fields_of_bundle = field_info_instances($entity_type, $bundle_name);
  $result = array();
  foreach ($fields_of_bundle as $key => $value) {
    if (is_array($value) && is_array($value['widget']) && $value['widget']['type'] == 'image_image') {
      $result[$key] = $value['label'] . " (" . $key . ")";
    }
  }
  return $result;
}

/**
 * calculate default value for settings form (more precisely image_field setting) of widget.
 * @param $widget
 * @param $image_fields
 */
function _histogram_get_field_widget_retreive_image_field_default_value($widget, $image_fields) {
  $result = $widget['settings']['image_field'];
  if (empty($result)) {
    $temp = array_keys($image_fields);
    if (!empty($temp) && is_array($temp)) {
      $result = $temp[0];
    }
  }
  return $result;
}

;

/**
 * implementation of #element_validate FAPI Hook
 */
function _histogram_field_widget_image_field_validate($element, &$form_state) {
  $image_field_settings = $form_state['values']['instance']['widget']['settings']['image_field'];
  if (empty($image_field_settings)) {
    form_error($element, t('you must choose at least one image field.'));
  }

}


function histogram_field_widget_error($element, $error, $form, &$form_state) {
  form_error($element, $error['message']);
}

function histogram_field_widget_validate($element, &$form_state) {
  //DO NOT CHANGE VALIDATION.
}
